name: Validate Nginx Configuration with WAF Rules

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  validate-nginx-configuration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download WAF rules
      run: |
        wget https://github.com/fabriziosalmi/patterns/releases/download/latest/nginx_waf.zip -O nginx_waf.zip
        echo "Downloaded nginx_waf.zip"
        ls -lh nginx_waf.zip

    - name: Extract WAF rules
      run: |
        unzip nginx_waf.zip -d waf_rules
        echo "Extracted WAF rules into waf_rules directory"
        ls -lh waf_rules/waf_patterns/nginx/

    - name: Verify WAF rules extraction
      run: |
        if [ ! -d "waf_rules/waf_patterns/nginx" ]; then
          echo "Error: WAF rules directory not found after extraction!"
          exit 1
        fi
        if [ -z "$(ls -A waf_rules/waf_patterns/nginx/*.conf 2>/dev/null)" ]; then
          echo "Error: No .conf files found in waf_rules/waf_patterns/nginx/"
          echo "Contents of waf_rules/waf_patterns/nginx/:"
          ls -l waf_rules/waf_patterns/nginx/
          exit 1
        fi

    - name: Verify nginx.conf exists
      run: |
        if [ ! -f "tests/nginx.conf" ]; then
          echo "Error: tests/nginx.conf not found in the repository!"
          exit 1
        fi

    - name: Validate individual WAF rule files
      run: |
        for file in waf_rules/waf_patterns/nginx/*.conf; do
          echo "Validating $file..."
          # Create a temporary nginx.conf file for validation
          echo "events {" > temp_nginx.conf
          echo "    worker_connections 1024;" >> temp_nginx.conf
          echo "}" >> temp_nginx.conf
          echo "http {" >> temp_nginx.conf
          echo "    include /etc/nginx/$(basename $file);" >> temp_nginx.conf
          echo "}" >> temp_nginx.conf

          # Debug: Print the temporary nginx.conf
          echo "Temporary nginx.conf for validation:"
          cat temp_nginx.conf

          # Validate the file using Docker
          docker run --rm -v $(pwd)/$file:/etc/nginx/$(basename $file):ro \
                         -v $(pwd)/temp_nginx.conf:/etc/nginx/nginx.conf:ro \
                         nginx nginx -t
          if [ $? -ne 0 ]; then
            echo "Error: Validation failed for $file"
            exit 1
          fi
        done

    - name: Validate Nginx configuration using Docker
      run: |
        # Copy the map directives, merged WAF rules, and nginx.conf to a Docker volume
        docker run --rm -v $(pwd)/map_directives.conf:/etc/nginx/map_directives.conf:ro \
                       -v $(pwd)/merged_waf_rules.conf:/etc/nginx/merged_waf_rules.conf:ro \
                       -v $(pwd)/tests/nginx.conf:/etc/nginx/tests/nginx.conf:ro \
                       -v $(pwd)/temp_nginx.conf:/etc/nginx/nginx.conf:ro \
                       nginx nginx -t